dataset_config:
  vqa_hat:
      data_dir: ${env.data_dir}/datasets
      depth_first: false
      fast_read: false
      use_images: true
      use_features: true
      zoo_requirements:
      - coco.subset_val
      - vqa2.defaults
      - vqa_hat.defaults
      images:
        train:
        - coco/subset_val/images/val2014
        val:
        - coco/subset_val/images/val2014
        test:
        - coco/subset_val/images/val2014
      features:
        train:
        - coco/subset_val/features/trainval2014.lmdb
        val:
        - coco/subset_val/features/trainval2014.lmdb
        test:
        - coco/subset_val/features/trainval2014.lmdb
      annotations:
        train:
          - vqa_hat/defaults/annotations/val.npy
        val:
          - vqa_hat/defaults/annotations/val.npy
        test:
          - vqa_hat/defaults/annotations/val.npy
      max_features: 100
      processors:
        text_processor:
          type: vocab
          params:
            max_length: 14
            vocab:
              type: intersected
              embedding_name: glove.6B.300d
              vocab_file: vqa2/defaults/extras/vocabs/vocabulary_100k.txt
            preprocessor:
              type: simple_sentence
              params: {}
        answer_processor:
          type: vqa_answer
          params:
            num_answers: 10
            vocab_file: vqa2/defaults/extras/vocabs/answers_vqa.txt
            preprocessor:
              type: simple_word
              params: {}
        context_processor:
          type: fasttext
          params:
            download_initially: false
            max_length: 50
            model_file: wiki.en.bin
        ocr_token_processor:
          type: simple_word
          params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 50
      return_features_info: false
      # Return OCR information
      use_ocr: false
      # Return spatial information of OCR tokens if present
      use_ocr_info: false
